// URL for NASA NEO (Near Earth Object) Feed API. Replace the key for production.
const url = 'https://api.nasa.gov/neo/rest/v1/feed?api_key=yLeK5umsbkYxahsLWuYq7XoeWgkseD3cZUXBdzVb';

// Audio / synth configuration
const notes = ["C3", "E3", "F3", "G3", "A3", "C4", "D4", "F4", "G4", "B4", "C5", "E6", "F6", "G6", "A6"];
let attackTime = 0.02;
let decayTime = 0.6;
let susPercent = 0.5;
let releaseTime = 2;

// Core state structures (refactor away from parallel arrays)
let asteroids = []; // array of { mag, distance, synth, intervalId }
let pulses = []; // visual pulses created when sounds play (rendered in draw)
let nasa; // JSON data loaded from API

// computed ranges used for mapping
let minMag, maxMag, minDistance, maxDistance;

// single reusable audio effects
let globalPolySynth;
let verb; // single Reverb instance reused across voices

// UI / runtime state
let scheduled = false; // prevent duplicate scheduling on repeated clicks
let dim; // min(width, height) for responsive sizing

// Scheduler state for WebAudio-timed events
let schedulerTimer = null;
const lookahead = 25; // ms between scheduler checks
const scheduleAheadTime = 0.5; // seconds to schedule ahead

// Rotation speed for visual animation (degrees per second)
const rotationSpeed = 2; // adjust to taste (original used frameCount/30)

function preload() {
  // Load the NASA feed JSON before setup runs so data is available immediately.
  // Note: embeded API key in a public repo is not recommended for production.
  nasa = loadJSON(url);
}

function setup() {
  // Create canvas and basic audio objects
  createCanvas(windowWidth, windowHeight);
  angleMode(DEGREES);
  noStroke();

  // poly synth available if desired
  globalPolySynth = new p5.PolySynth();

  // single reverb instance shared by per-asteroid synths
  verb = new p5.Reverb();

  // Build visualization and audio voices from loaded data
  drawViz();
}

function mousePressed() {
  // Start audio (browser requires a user gesture) and initialize scheduler.
  if (scheduled) return; // avoid duplicate scheduling on multiple clicks
  console.log('start');
  userStartAudio();

  if (!asteroids || asteroids.length === 0) return;

  const ac = getAudioContext();
  const now = ac.currentTime;

  // compute per-asteroid period (seconds) and initial nextTime
  asteroids.forEach((a) => {
    // map distance -> period in seconds (closer => more frequent)
    const seconds = map(a.distance, minDistance, maxDistance, 2, 32);
    a.period = Math.max(0.2, seconds); // minimum 0.2s
    // schedule first event slightly in the future to allow scheduling window
    a.nextTime = now + Math.random() * 0.5; // jitter start within 0.5s
  });

  // start the scheduler loop which will use audioContext.currentTime
  startScheduler();
  scheduled = true;
}

function draw() {
  // store the dimensions 
  dim = Math.min(width, height);
  // Render background and center Earth
  translate(width / 2, height / 2);
  background("#222222");
  fill(220);
  ellipse(0, 0, 20); // center earth

  // early exit if no asteroid data
  if (!asteroids || asteroids.length === 0) return;

  // rotation amount for animation (use time-based rotation for scheduler consistency)
  let r = (millis() / 1000) * rotationSpeed;

  // draw orbit rings first
  for (let i = 0; i < asteroids.length; i++) {
    const a = asteroids[i];
    const orbitRadius = map(a.distance, minDistance, maxDistance, 10 * (dim * 0.01), 40 * (dim * 0.01));
    stroke(100);
    noFill();
    ellipse(0, 0, orbitRadius * 2, orbitRadius * 2);
  }

  // draw asteroids on their rings
  for (let i = 0; i < asteroids.length; i++) {
    const a = asteroids[i];
    const orbitRadius = map(a.distance, minDistance, maxDistance, 10 * (dim * 0.01), 40 * (dim * 0.01));
    const sizeScaled = map(a.mag, minMag, maxMag, 80 * (dim * 0.001), 5 * (dim * 0.001));

    push();
    rotate(r + i * (360 / asteroids.length));
    noStroke();
    fill(180);
    ellipse(0, orbitRadius, sizeScaled, sizeScaled);
    pop();
  }

  // draw pulses generated by playNote (these live for a short lifetime)
  for (let i = pulses.length - 1; i >= 0; i--) {
    const p = pulses[i];
    const age = millis() - p.created;
    // not yet time to display this pulse
    if (age < 0) continue;
    if (age > p.lifetime) {
      pulses.splice(i, 1);
      continue;
    }
    const alpha = map(age, 0, p.lifetime, 255, 0);
    
    push();
    noFill();
    stroke(255, alpha);
    strokeWeight(2);
    // draw at stored x,y so the pulse lines up with the asteroid's ring
    ellipse(0, 0, p.size);
    pop();
  }
}

function drawViz() {
  // Build the `asteroids` array from the loaded NASA JSON.
  if (!nasa || !nasa.near_earth_objects) return;

  // Choose today's key if available, otherwise use the first available day
  const keys = Object.keys(nasa.near_earth_objects);
  if (keys.length === 0) return;
  const today = new Date().toISOString().split('T')[0];
  const dayKey = nasa.near_earth_objects[today] ? today : keys[0];
  const sats = nasa.near_earth_objects[dayKey];

  asteroids = [];
  for (let i = 0; i < sats.length; i++) {
    const mag = +sats[i].absolute_magnitude_h;
    const distance = +sats[i].close_approach_data[0].miss_distance.lunar;

    // create a MonoSynth voice for this asteroid and attach global reverb
    const sy = new p5.MonoSynth();
    verb.process(sy, 3, 2); // shorter reverb for better clarity
    sy.setADSR(attackTime, decayTime, susPercent, releaseTime);

    asteroids.push({ mag, distance, synth: sy, intervalId: null });
  }

  // compute min/max ranges for mapping
  const mags = asteroids.map(a => a.mag);
  const dists = asteroids.map(a => a.distance);
  if (mags.length === 0) return;
  maxMag = max(mags);
  minMag = min(mags);
  minDistance = min(dists);
  maxDistance = max(dists);

  console.log('mag range', minMag, maxMag);
} 

function playNote(index, noteIndex, timing) {
  // Trigger audio for asteroid at `index` using a precomputed noteIndex.
  if (!asteroids[index]) return;
  const a = asteroids[index];
  const vel = 0.1;
  const time = 0;
  const dur = 0.3;

  // safeguard noteIndex
  const ni = Math.max(0, Math.min(noteIndex, notes.length - 1));
  a.synth.play(notes[ni], vel, time, dur);

  // push a visual pulse (drawn from draw() to avoid drawing inside timer)
  const size = map(timing, 200, 32000, 50, 800);
  pulses.push({ created: millis(), lifetime: 1000, size });
}

// stop scheduled intervals and reset scheduling state
function stopAllIntervals() {
  asteroids.forEach(a => {
    if (a.intervalId) {
      clearInterval(a.intervalId);
      a.intervalId = null;
    }
  });
  scheduled = false;
}

function windowResized() {
  resizeCanvas(windowWidth, windowHeight);
}

// --- WebAudio scheduler -------------------------------------------------
function startScheduler() {
  if (schedulerTimer) return;
  schedulerTimer = setTimeout(schedulerLoop, lookahead);
}

function stopScheduler() {
  if (schedulerTimer) {
    clearTimeout(schedulerTimer);
    schedulerTimer = null;
  }
}

function schedulerLoop() {
  const ac = getAudioContext();
  const currentTime = ac.currentTime;
  const scheduleWindow = currentTime + scheduleAheadTime;

  // For each asteroid, schedule any events that should occur within the window
  asteroids.forEach((a, i) => {
    // compute noteIndex for this asteroid (magnitude -> pitch mapping)
    const val = map(a.mag, minMag, maxMag, notes.length - 1, 0);
    const rawIndex = round(val);
    const noteIndex = Math.max(0, Math.min(rawIndex, notes.length - 1));

    // schedule all occurrences that fall within the schedule window
    while (a.nextTime <= scheduleWindow) {
      const secondsFromNow = Math.max(0, a.nextTime - currentTime);
      // use the synth's startTime parameter (seconds from now)

      a.synth.play(notes[noteIndex], 0.1, secondsFromNow, 0.3);

      // schedule a visual pulse at the appropriate future moment and position
      const scheduledMillis = millis() + secondsFromNow * 1000;
      // compute angular position at scheduled time (degrees)
      const angleDeg = (scheduledMillis / 1000) * rotationSpeed + i * (360 / asteroids.length);
      const angleRad = radians(angleDeg);
      const orbitRadius = map(a.distance, minDistance, maxDistance, 10 * (dim * 0.01), 40 * (dim * 0.01));
      // convert polar to cartesian to match rotate()+ellipse(0, orbitRadius):
      // rotated point (0, R) -> world x = -R * sin(theta), y = R * cos(theta)
      const x = -orbitRadius * sin(angleRad);
      const y = orbitRadius * cos(angleRad);
      // use the orbit's diameter so the pulse matches the ring size
      const size = orbitRadius * 2;
      pulses.push({ created: scheduledMillis, lifetime: 1000, size, x, y });

      // advance to the next scheduled time for this asteroid
      a.nextTime += a.period;
    }
  });

  // queue the next scheduler tick
  schedulerTimer = setTimeout(schedulerLoop, lookahead);
}
